name: Unit testing with pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test with pytest
      run: pytest test_matrix_multiplication.py
      
    - name: Upload plot image
      uses: actions/upload-artifact@v2
      with:
        name: matrix-multiplication-plot
        path: plot.png
        
    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: matrix-multiplication-log
        path: output.log
